service: core-service-ext-storage

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally

provider:
  name: aws
  stage: dev
  region: ap-southeast-1

resources:
  Resources:
    MediaBucket: ${file(../resources/MediaBucket.yml):MediaBucket}