service: core-service-ext-database

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally

provider:
  name: aws
  stage: dev
  region: ap-southeast-1

resources:
  Resources:
    UserTable: ${file(../resources/UserTable.yml):UserTable}
    UnitParkingTable: ${file(../resources/UnitParkingTable.yml):UnitParkingTable}
    DeviceTable: ${file(../resources/DeviceTable.yml):DeviceTable}
    # DocumentTable: ${file(../resources/DocumentTable.yml):DocumentTable}
    ParkingSessionTable: ${file(../resources/ParkingSessionTable.yml):ParkingSessionTable}

  Outputs:
    UserTableArn:
      Value:
        Fn::GetAtt:
          - UserTable
          - Arn
      Export:
        Name: ${self:custom.stage}-UserTableArn
    # DocumentTableArn:
    #   Value:
    #     Fn::GetAtt:
    #       - DocumentTable
    #       - Arn
    #   Export:
    #     Name: ${self:custom.stage}-DocumentTableArn
    UnitParkingTableArn:
      Value:
        Fn::GetAtt:
          - UnitParkingTable
          - Arn
      Export:
        Name: ${self:custom.stage}-UnitParkingTableArn
    DeviceTableArn:
      Value:
        Fn::GetAtt:
          - DeviceTable
          - Arn
      Export:
        Name: ${self:custom.stage}-DeviceTableArn
    ParkingSessionTableArn:
      Value:
        Fn::GetAtt:
          - ParkingSessionTable
          - Arn
      Export:
        Name: ${self:custom.stage}-ParkingSessionTableArn
