DeviceTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: DeviceTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: deviceType
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: deviceTypeIndex
        KeySchema:
          - AttributeName: deviceType
            KeyType: HASH
        Projection:
          ProjectionType: ALL
