UnitParkingTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: UnitParkingTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: type
        AttributeType: N
      - AttributeName: totalCabin
        AttributeType: N
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: TypeAndTotalCabin
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: totalCabin
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
