UserTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: UserTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: userType
        AttributeType: N
      - AttributeName: phone
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: phoneAndUserType
        KeySchema:
          - AttributeName: phone
            KeyType: HASH
          - AttributeName: userType
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
